- name: Install and another
  hosts: servers
  become: true
  vars:
    required_Pkg:
      - apache2
      - python3-urllib3
    web_Service: apache2
    content_File: "adinusa lab quiz variables - arigints"
    dest_File: /var/www/html/index.html

  tasks:
    - name: install required package
      apt: name="{{required_Pkg}}" state=latest

    - name: ensure the apache is enabled
      service:
        name: "{{web_Service}}"
        state: started
        enabled: true

    - name: web content is in place
      copy:
        content: "{{content_File}}"
        dest: "{{dest_File}}"

- name: Verify the web server is accessible
  hosts: localhost
  tasks:
    - name: testing web server
      uri:
        url: http://pod-arigints-managed2/index.html
        status_code: 200
        return_content: yes
